apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: function-split
  namespace: project
spec:
  service: load-service
  backends:
  - service: go-client-service
    weight: 500m
  - service: redis-client-service
    weight: 500m
